<?php
// add edit links everywhere
function edit($nid) {
  if (user_access('administer nodes')) {
     $url = url('node/'.$nid.'/edit?detination='.$_GET['q']);
     $url = substr($url,1,strlen($url)-1);
     $options['attributes']['class'] = 'edit-link';
     return l('edit',$url,$options);
  } else { return null; }
}
function theme_tweaks_preprocess_node(&$vars) {
	$vars['body'] = $vars['node']->content['body']['#value'];
}

function back_url($default = false){
	if (preg_match('/'.$_SERVER['HTTP_HOST'].'/i', $_SERVER['HTTP_REFERER'])) {
		$back_url = $_SERVER['HTTP_REFERER'];
	}
	else if($default) {
		$back_url = url($default);
	}

	return $back_url;
}

function strip_site_url($string = null) {
	
	$string = str_replace($_SERVER['HTTP_HOST'].'/','',$string);
	$string = str_replace('http://','',$string);
	$string = str_replace('https://','',$string);
	return $string;
	
}

function plural_check($count) {
	return $count == 1 ? '' : 's';
}

function tweaks_trim_text($alter, $value) {
  if (drupal_strlen($value) > $alter['max_length']) {
    $value = drupal_substr($value, 0, $alter['max_length']);
    // TODO: replace this with cleanstring of ctools
    if (!empty($alter['word_boundary'])) {
      $regex = "(.*)\b.+";
      if (function_exists('mb_ereg')) {
        mb_regex_encoding('UTF-8');
        $found = mb_ereg($regex, $value, $matches);
      }
      else {
        $found = preg_match("/$regex/us", $value, $matches);
      }
      if ($found) {
        $value = $matches[1];
      }
    }
    // Remove scraps of HTML entities from the end of a strings
    $value = rtrim(preg_replace('/(?:<(?!.+>)|&(?!.+;)).*$/us', '', $value));

    if (!empty($alter['ellipsis'])) {
      $value .= '...';
    }
  }
  if (!empty($alter['html'])) {
    $value = _filter_htmlcorrector($value);
  }

  return $value;
}
/*
 * Implements hook_form_alter()
*/

function theme_tweaks_form_alter(&$form, &$form_state, $form_id) {
  /**
   * Removes the unnecessary preview button, if you have anything against it.
   * Does NOT check to ensure preview is optional!  Make preview optional first.
   */
  unset ($form['buttons']['preview']);
}
?>